### ISSUE TITLE
The package “controlP5” does not exist. I might be missing a library.

### ISSUE THREAD

**Issue by haesleinhuepf** [mutterer/processingLiveImageJMacros#1]
Hi @mutterer ,

thanks for sharing this; it looks really powerful! I know, it's just a prototype, however could you please provide some more details on installation instructions? I downloaded processing-3.5.2 for Win64. When I try to run your tool, I get this error message:
![image](https://user-images.githubusercontent.com/12660498/52163735-a9865f00-26e6-11e9-95ca-741e276c11ae.png)

Can you please point me to these libraries? Do they come bundled with a special version of processing from somewhere?

Thanks a lot in advance!

Cheers,
Robert

**Comment by mutterer** [comment]
I've added instructions about installing libraries. Thanks for asking.

**Comment by haesleinhuepf** [comment]
Great! 

Now it works :-)

Nevertheless, I'd be happy if you could give me a short introduction to processing.org - seems like an amazing tool!

Thanks!
